import gymnasium as gym
"""
This file demonstrates the creation of a custom Gymnasium RewardWrapper for the
environment.

The primary goal of this specific wrapper, `TimePenaltyRewardWrapper`, is to
modify the reward signal that the reinforcement learning agent receives from
the base environment. It achieves this by applying a small, constant negative
penalty at every time step, in addition to any rewards (or penalties) already
generated by the underlying `FireFightingEnv`.

This technique, known as "reward shaping," is commonly used in reinforcement
learning to encourage agents to complete tasks more efficiently or quickly.
By adding a continuous time penalty, the agent is encouraged to find optimal
policies that minimize the number of steps taken to reach a positive reward
or a terminal state.

For more details on Gymnasium wrappers, refer to the official documentation:
https://gymnasium.farama.org/api/wrappers/
"""

class TimePenaltyRewardWrapper(gym.RewardWrapper):
    """
    A custom Gymnasium RewardWrapper that adds a small negative penalty
    to the reward received by the agent at each step.

    This wrapper encourages the agent to solve the task more efficiently by
    penalizing prolonged episodes, guiding it towards policies that minimize
    the number of actions taken to achieve its objectives.
    """
    def __init__(self, env, step_penalty=-0.1):
        """
        Initializes the TimePenaltyRewardWrapper.

        Args:
            env (gym.Env): The Gymnasium environment to wrap.
            step_penalty (float, optional): The constant negative reward
                                            to subtract at each time step.
                                            Defaults to -0.1.
        """
        super().__init__(env)
        self.step_penalty = step_penalty

    def reward(self, reward):
        """
        Modifies the original reward by adding the predefined time penalty.

        This method is automatically called by the Gymnasium environment
        after each `step()` call to modify the reward before it's returned
        to the agent.

        Args:
            reward (float): The original reward generated by the wrapped environment.

        Returns:
            float: The modified reward, incorporating the time penalty.
        """
        return reward + self.step_penalty
