import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

"""
This script provides a suite of visualization tools for analyzing the performance
metrics generated by the environment.

It reads the `metrics.csv` file, which is expected to be populated by running
either the main simulation script (`run_simulation.py`) or the PPO training script
(`train_ppo.py`). Using the `pandas`, `matplotlib`, and `seaborn` libraries,
it generates and saves a series of plots that offer insights into agent
performance across various dimensions.

The generated plots include:
- A line plot tracking final scores over episodes to show learning trends.
- A bar chart showing the distribution of final outcomes (SUCCESS, TIMEOUT, CRASH).
- A scatter plot correlating the number of steps taken with the final score.
- A box plot comparing the fire extinguish rates between different agents.

To use this script, first run a simulation to generate the `metrics.csv` file,
then execute this script from the same root directory. The output plots will be
saved in the `metrics/` directory.
"""

def plot_score_over_episodes(df):
    """
    Generates and saves a line plot showing the final score achieved by each
    agent type across different episodes.

    The plot visualizes trends in agent performance over time, making it easy
    to compare how different agents' scores evolve.

    Args:
        df (pd.DataFrame): A Pandas DataFrame containing simulation metrics,
                           expected to have 'episode', 'final_score', and 'agent_type' columns.
    """

    plt.figure(figsize=(12, 7))
    sns.lineplot(data=df, x='episode', y='final_score', hue='agent_type', style='agent_type', markers=True,
                 dashes=False)
    plt.title('Agent Final Score per Episode', fontsize=16)
    plt.xlabel('Episode Number')
    plt.ylabel('Final Score')
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.legend(title='Agent Type')
    plt.tight_layout()
    plt.savefig('metrics/score_vs_episode.png')
    print("Generated score_vs_episode.png")


def plot_outcome_distribution(df):
    """
    Generates and saves a bar chart illustrating the distribution of episode
    outcomes (SUCCESS, TIMEOUT, CRASH) for each agent type.

    This plot helps in understanding the robustness and success rate of agents
    under various conditions.

    Args:
        df (pd.DataFrame): A Pandas DataFrame containing simulation metrics,
                           expected to have 'outcome' and 'agent_type' columns.
    """

    plt.figure(figsize=(10, 6))
    # Using 'dodge' for side-by-side bars if multiple agents are present
    sns.countplot(data=df, x='outcome', hue='agent_type', dodge=True,
                  order=['SUCCESS', 'TIMEOUT', 'CRASH'])  # Ensures consistent bar order
    plt.title('Distribution of Episode Outcomes by Agent', fontsize=16)
    plt.xlabel('Outcome')
    plt.ylabel('Number of Episodes')
    plt.tight_layout()
    plt.savefig('metrics/outcome_distribution.png')
    print("Generated outcome_distribution.png")


def plot_steps_vs_score(df):
    """
    Generates and saves a scatter plot that visualizes the relationship between
    the number of steps taken in an episode and the final score achieved,
    distinguishing by agent type and outcome.

    This plot can reveal insights into agent efficiency and how different
    outcomes correlate with episode length and score.

    Args:
        df (pd.DataFrame): A Pandas DataFrame containing simulation metrics,
                           expected to have 'steps_taken', 'final_score', 'agent_type', and 'outcome' columns.
    """
    plt.figure(figsize=(12, 7))
    sns.scatterplot(data=df, x='steps_taken', y='final_score', hue='agent_type', style='outcome', s=100)
    plt.title('Steps Taken vs. Final Score', fontsize=16)
    plt.xlabel('Steps Taken per Episode')
    plt.ylabel('Final Score')
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.legend(title='Agent & Outcome')
    plt.tight_layout()
    plt.savefig('metrics/steps_vs_score.png')
    print("Generated steps_vs_score.png")


def plot_extinguish_rate(df):
    """
    Generates and saves a box plot showing the distribution of fire
    extinguish rates for each agent type. Individual episode data points
    are overlaid as a stripplot.

    The extinguish rate is calculated as `fires_extinguished / fires_total`.
    This plot helps assess how effectively each agent manages to eliminate fires.

    Args:
        df (pd.DataFrame): A Pandas DataFrame containing simulation metrics,
                           expected to have 'fires_extinguished', 'fires_total', and 'agent_type' columns.
    """
    df['extinguish_rate'] = (df['fires_extinguished'] / df['fires_total']).fillna(0)

    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df, x='agent_type', y='extinguish_rate')
    sns.stripplot(data=df, x='agent_type', y='extinguish_rate', color=".25", alpha=0.6)  # Overlay individual points
    plt.title('Fire Extinguish Rate by Agent', fontsize=16)
    plt.xlabel('Agent Type')
    plt.ylabel('Extinguish Rate (Extinguished / Total)')
    plt.ylim(0, 1.05)  # Set y-axis from 0% to 105%
    plt.grid(True, axis='y', linestyle='--', linewidth=0.5)
    plt.tight_layout()
    plt.savefig('metrics/extinguish_rate.png')
    print("Generated extinguish_rate.png")


def main():
    """
    Main function to load simulation metrics from a CSV file and generate a series
    of analytical plots.

    It checks for the existence of the metrics file, loads the data, sets a
    professional plotting style, and then calls individual plotting functions
    to visualize different aspects of agent performance.
    """
    csv_file_path = 'metrics/metrics.csv'

    if not os.path.isfile(csv_file_path):
        print(f"Error: The file '{csv_file_path}' was not found.")
        print("Please run the main challenge script first to generate metrics.")
        return

    print(f"Loading metrics from '{csv_file_path}'...")
    # Load the data using pandas
    try:
        df = pd.read_csv(csv_file_path)
    except pd.errors.EmptyDataError:
        print(f"Error: The file '{csv_file_path}' is empty. No data to plot.")
        return

    # Set a professional plot style
    sns.set_theme(style="whitegrid")

    # Generate all plots
    print("\nGenerating plots...")
    plot_score_over_episodes(df)
    plot_outcome_distribution(df)
    plot_steps_vs_score(df)
    plot_extinguish_rate(df)

    print("\nAll plots have been saved as PNG files in the current directory.")

    # Use plt.show() if you want to display the plots interactively after saving
    # plt.show()


if __name__ == '__main__':
    main()
